# Standarization

In [7]:
from sklearn import preprocessing
import numpy as np

x=np.array([[-400],[-100],[0],[100],[400]])

standardscaler=preprocessing.StandardScaler()
x_scaler=standardscaler.fit_transform(x)

print(x_scaler)


x1=np.array([[1,2,3],[4,5,6],[7,8,9]])
standardscaler1=preprocessing.StandardScaler()

x_scaler1=standardscaler1.fit_transform(x1)
print(x_scaler1)

[[-1.53392998]
 [-0.38348249]
 [ 0.        ]
 [ 0.38348249]
 [ 1.53392998]]
[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


# Normalization

In [6]:
from sklearn import preprocessing
import numpy as np

x=np.array([[1,2],[2,5],[3,6],[4,9],[5,8]])

normalizer=preprocessing.Normalizer()
normal=normalizer.fit_transform(x)

print(normal)


x1=np.array([[1,2,3],[4,5,6],[7,8,9]])
normalizer1=preprocessing.Normalizer()

normal1=normalizer1.fit_transform(x1)
print(normal1)

[[0.4472136  0.89442719]
 [0.37139068 0.92847669]
 [0.4472136  0.89442719]
 [0.40613847 0.91381155]
 [0.52999894 0.8479983 ]]
[[0.26726124 0.53452248 0.80178373]
 [0.45584231 0.56980288 0.68376346]
 [0.50257071 0.57436653 0.64616234]]


# Binarizer

In [1]:
from sklearn import preprocessing
import numpy as np

x=np.array([[1,2],[2,5],[3,6],[4,9],[5,8]])

binarizer=preprocessing.Binarizer(4)
binarizer_scaled=binarizer.fit_transform(x)

print(binarizer_scaled)


x1=np.array([[1,2,3],[4,5,6],[7,8,9]])
binarizer1=preprocessing.Binarizer(5)

binarizer_scaled1=binarizer1.fit_transform(x1)
print(binarizer_scaled1)

[[0 0]
 [0 1]
 [0 1]
 [0 1]
 [1 1]]
[[0 0 0]
 [0 0 1]
 [1 1 1]]


# Robust Scaler

In [3]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
x=np.array([[-500],[-100],[0],[100],[900]])
robust=preprocessing.RobustScaler()
x_robust=robust.fit_transform(x)

Q1=np.percentile(x,25)
Q2=np.percentile(x,50)
Q3=np.percentile(x,75)

print('Lower Quartile:',Q1)
print('Medium:',Q2)
print('Upper Quartile:',Q3)

robust_scaler1=(x-Q2)/(Q3-Q1)
print(robust_scaler1)
#####################################################################


x1=np.array([[2,2,3],[4,5,6],[7,8,9]])
robust_scaler2=robust.fit_transform(x1)
print(robust_scaler2)

Lower Quartile: -100.0
Medium: 0.0
Upper Quartile: 100.0
[[-2.5]
 [-0.5]
 [ 0. ]
 [ 0.5]
 [ 4.5]]
[[-0.8 -1.  -1. ]
 [ 0.   0.   0. ]
 [ 1.2  1.   1. ]]


# MaxAbs Scaler

In [4]:
from sklearn import preprocessing
import numpy as np

x=np.array([[-500.5],[-100.1],[0],[100.1],[900.9]])

maxabs=preprocessing.MaxAbsScaler()
x_scaled=maxabs.fit_transform(x)

print(x_scaled)

x1=np.array([[1,2,3],[-4,5,-6],[7,-8,9]])

x_scaled2=maxabs.fit_transform(x1)

print(x_scaled2)

import pandas as pd

df=pd.DataFrame(np.random.randn(4,5),columns=np.arange(5))
print(df)

x_scaled3=maxabs.fit_transform(df)
print(x_scaled3)

[[-0.55555556]
 [-0.11111111]
 [ 0.        ]
 [ 0.11111111]
 [ 1.        ]]
[[ 0.14285714  0.25        0.33333333]
 [-0.57142857  0.625      -0.66666667]
 [ 1.         -1.          1.        ]]
          0         1         2         3         4
0  1.067854  1.962566  1.353087  0.121282 -1.101811
1  0.347087 -1.136351  0.197415  1.017082 -0.799175
2  0.835230  1.404004  0.586439 -0.062601 -0.560789
3 -0.704364 -0.357857 -0.445355 -0.453031  0.577577
[[ 1.          1.          1.          0.11924533 -1.        ]
 [ 0.32503236 -0.57901291  0.14589987  1.         -0.72532861]
 [ 0.78215786  0.71539196  0.43340799 -0.06154979 -0.50896978]
 [-0.65960731 -0.1823414  -0.32913949 -0.44542254  0.52420722]]


# MinMax Scaler

In [5]:
from sklearn import preprocessing
import numpy as np

x=np.array([[-400],[-100],[0],[100],[400]])

minmaxscaler=preprocessing.MinMaxScaler(feature_range=(0,1))
x_scaler=minmaxscaler.fit_transform(x)

print(x_scaler)


x1=np.array([[1,2,3],[4,5,6],[7,8,9]])
minmaxscaler1=preprocessing.MinMaxScaler(feature_range=(0,1))

x_scaler1=minmaxscaler1.fit_transform(x1)
print(x_scaler1)

[[0.   ]
 [0.375]
 [0.5  ]
 [0.625]
 [1.   ]]
[[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]


# Inversed Transformed

In [8]:
from sklearn import preprocessing
import numpy as np

x=np.array([[-400],[-100],[0],[100],[400]])

standardscaler=preprocessing.StandardScaler()
x_scaler=standardscaler.fit_transform(x)

print(x_scaler)
x_scaledback=standardscaler.inverse_transform(x_scaler)
print(x_scaledback)


##############################################

x=np.array([[-400],[-100],[0],[100],[400]])

minmaxscaler=preprocessing.MinMaxScaler(feature_range=(0,1))
x_scaler=minmaxscaler.fit_transform(x)

print(x_scaler)
x_minmax_scaleback=minmaxscaler.inverse_transform(x_scaler)
print(x_minmax_scaleback)

[[-1.53392998]
 [-0.38348249]
 [ 0.        ]
 [ 0.38348249]
 [ 1.53392998]]
[[-400.]
 [-100.]
 [   0.]
 [ 100.]
 [ 400.]]
[[0.   ]
 [0.375]
 [0.5  ]
 [0.625]
 [1.   ]]
[[-400.]
 [-100.]
 [   0.]
 [ 100.]
 [ 400.]]
